services:
 
  VPN_Server:
    build: ./VPN_ubuntu_server
    image:  vpn_server
    container_name: vpn_server-192.168.40.20
    hostname: vpn_server
    tty: true
    cap_add:
      - ALL
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      net-192.168.40.0:
        ipv4_address: 192.168.40.20
      net-172.16.50.0:
        ipv4_address: 172.16.50.20
    volumes:
      - ./server_scripts:/media/scripts
  
  VPN_Client:
    build: ./VPN_ubuntu_client
    image:  vpn_client
    container_name: vpn_client-192.168.40.10
    hostname: vpn_client
    tty: true
    cap_add:
      - ALL
    devices:
      - "/dev/net/tun:/dev/net/tun"
    networks:
      net-192.168.40.0:
        ipv4_address: 192.168.40.10
    volumes:
      - ./client_scripts:/media/scripts

  Host:
    build: ./VPN_ubuntu_host
    image:  host
    container_name: host-172.16.50.10
    hostname: host
    tty: true
    cap_add:
      - ALL
    networks:
      net-172.16.50.0:
        ipv4_address: 172.16.50.10
    command: bash -c 'ip route del default  &&
                      ip route add default via 172.16.50.20 &&
                      /etc/init.d/openbsd-inetd start &&
                      tail -f /dev/null'
  
networks:
  net-192.168.40.0:
    name: net-192.168.40.0
    ipam:
      config:
        - subnet: 192.168.40.0/24

  net-172.16.50.0:
    name: net-172.16.50.0
    ipam:
      config:
        - subnet: 172.16.50.0/24
        